services:
  backend:
    container_name: ceviche_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    restart: always
    networks:
      - default
      - prod_network

  frontend:
    container_name: ceviche_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    restart: always
    networks:
      - default
      - prod_network

volumes:
  static_volume:
    name: ceviche_static_volume
  media_volume:
    name: ceviche_media_volume

networks:
  prod_network:
    external: true
  default:
    name: ceviche-placosones_default
